{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-secret",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "foo": "AgB24tAaIka+Qx68wYJjnOtig/H1Xm0Qp0DE+uZNNL22FoUnYZFY0BmMpM2zB/SKg4rASfw8yR+I5Y4s242l+ZF53tTVFUfB4yuBQ0uT83z+Am9b4HZh6Fg0qj9syJWehz+Q62tqRr1wLq01mZlI5FWkFvRPfaq1QDAvxD/lFY0tZ9GyZim5hF39l5V7HkHpsQ92UMFlRaeE/rm8gePkS8PpjtMrDqwluYFMsxvzw+/lhkS6SJnL2ywqlWx56mNH8Z9Ajd15Uis3BqnOnJd+nz8RKtd+agirB/TFUNchizhF4Vr7WdyMrcVwEKwDJOIfFG213No1/S2E47FwOEG2r7Z8TqTQR2OV1G7Oc2ZuUiCzh//XNAvallsiJSNzE7Il1GnudOLr6k0qGCSD/v+Y+qtkdiDB/W4M2jOKy0DWdgqMRm9fXAUaGWfb7BeJhCHnqrTN3/XErD1uWe8QmDpL17QfHtnZuCLVgH7oxpwTN6DNVGsc1XSJ/fbeOJyrBSIhgJ49i/igVWC11LWUF4jSqfbGeSA/urlMstYXv/c0lnkDI57oLPsyeovR9ZpXEK/x5erDwympi4R6zXRk0FqvaTXIUxsZWEnMYQY7bEVEIZcNFRqjnJtxZgDRdPK8N4q2yINHadf+A0nHkMG4Cwur2QFf/slPWh48Gt65nYH7nnIA41To8riU/J+eHwy3bByRYblENVw="
    }
  }
}
