apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-config
data:
  config.json: |
    {
      "environment" : "development"
    }
# kubectl create configmap lab-config --from-file ./golang/configs/config.json
